
package Sudoku.Server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RevisedSudokuServer", targetNamespace = "Sudoku", wsdlLocation = "http://localhost:9876/Sudoku?wsdl")
public class RevisedSudokuServer
    extends Service
{

    private final static URL REVISEDSUDOKUSERVER_WSDL_LOCATION;
    private final static WebServiceException REVISEDSUDOKUSERVER_EXCEPTION;
    private final static QName REVISEDSUDOKUSERVER_QNAME = new QName("Sudoku", "RevisedSudokuServer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9876/Sudoku?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REVISEDSUDOKUSERVER_WSDL_LOCATION = url;
        REVISEDSUDOKUSERVER_EXCEPTION = e;
    }

    public RevisedSudokuServer() {
        super(__getWsdlLocation(), REVISEDSUDOKUSERVER_QNAME);
    }

    public RevisedSudokuServer(WebServiceFeature... features) {
        super(__getWsdlLocation(), REVISEDSUDOKUSERVER_QNAME, features);
    }

    public RevisedSudokuServer(URL wsdlLocation) {
        super(wsdlLocation, REVISEDSUDOKUSERVER_QNAME);
    }

    public RevisedSudokuServer(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REVISEDSUDOKUSERVER_QNAME, features);
    }

    public RevisedSudokuServer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RevisedSudokuServer(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AnnotatedSudokuServer
     */
    @WebEndpoint(name = "AnnotatedSudokuServerPort")
    public AnnotatedSudokuServer getAnnotatedSudokuServerPort() {
        return super.getPort(new QName("Sudoku", "AnnotatedSudokuServerPort"), AnnotatedSudokuServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnnotatedSudokuServer
     */
    @WebEndpoint(name = "AnnotatedSudokuServerPort")
    public AnnotatedSudokuServer getAnnotatedSudokuServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("Sudoku", "AnnotatedSudokuServerPort"), AnnotatedSudokuServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REVISEDSUDOKUSERVER_EXCEPTION!= null) {
            throw REVISEDSUDOKUSERVER_EXCEPTION;
        }
        return REVISEDSUDOKUSERVER_WSDL_LOCATION;
    }

}
