
package Scrabble.Server;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PuzzleUtilityService", targetNamespace = "http://PuzzleUtilityURI.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PuzzleUtilityService {


    /**
     * 
     */
    @WebMethod(operationName = "Scrabble_CheckBoard", action = "http://PuzzleUtilityURI.org/Scrabble_CheckBoard")
    @RequestWrapper(localName = "Scrabble_CheckBoard", targetNamespace = "http://PuzzleUtilityURI.org/", className = "Scrabble.Server.ScrabbleCheckBoard")
    @ResponseWrapper(localName = "ScrabbleResponse", targetNamespace = "http://PuzzleUtilityURI.org/", className = "Scrabble.Server.ScrabbleResponse")
    @Action(input = "http://PuzzleUtilityURI.org/Scrabble_CheckBoard", output = "http://PuzzleUtilityURI.org/PuzzleUtilityService/Scrabble_CheckBoardResponse")
    public void scrabbleCheckBoard();

}
