
package Scrabble.Server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PuzzleUtilityServiceService", targetNamespace = "http://PuzzleUtilityURI.org/", wsdlLocation = "http://127.0.0.1:9876/PuzzleUtility?wsdl")
public class PuzzleUtilityServiceService
    extends Service
{

    private final static URL PUZZLEUTILITYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PUZZLEUTILITYSERVICESERVICE_EXCEPTION;
    private final static QName PUZZLEUTILITYSERVICESERVICE_QNAME = new QName("http://PuzzleUtilityURI.org/", "PuzzleUtilityServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9876/PuzzleUtility?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUZZLEUTILITYSERVICESERVICE_WSDL_LOCATION = url;
        PUZZLEUTILITYSERVICESERVICE_EXCEPTION = e;
    }

    public PuzzleUtilityServiceService() {
        super(__getWsdlLocation(), PUZZLEUTILITYSERVICESERVICE_QNAME);
    }

    public PuzzleUtilityServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUZZLEUTILITYSERVICESERVICE_QNAME, features);
    }

    public PuzzleUtilityServiceService(URL wsdlLocation) {
        super(wsdlLocation, PUZZLEUTILITYSERVICESERVICE_QNAME);
    }

    public PuzzleUtilityServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUZZLEUTILITYSERVICESERVICE_QNAME, features);
    }

    public PuzzleUtilityServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PuzzleUtilityServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PuzzleUtilityService
     */
    @WebEndpoint(name = "PuzzleUtilityServicePort")
    public PuzzleUtilityService getPuzzleUtilityServicePort() {
        return super.getPort(new QName("http://PuzzleUtilityURI.org/", "PuzzleUtilityServicePort"), PuzzleUtilityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PuzzleUtilityService
     */
    @WebEndpoint(name = "PuzzleUtilityServicePort")
    public PuzzleUtilityService getPuzzleUtilityServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://PuzzleUtilityURI.org/", "PuzzleUtilityServicePort"), PuzzleUtilityService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUZZLEUTILITYSERVICESERVICE_EXCEPTION!= null) {
            throw PUZZLEUTILITYSERVICESERVICE_EXCEPTION;
        }
        return PUZZLEUTILITYSERVICESERVICE_WSDL_LOCATION;
    }

}
