/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puzzleutilityservice;

/**
 *
 * @author Brad
 */
public class Form_Main extends javax.swing.JFrame {

    /**
     * Creates new form Form_Main
     */
    public Form_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        button_Sudoku = new javax.swing.JButton();
        button_Scrabble = new javax.swing.JButton();
        button_TTT = new javax.swing.JButton();
        button_Dictionary = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Puzzle Game Utility Service");

        button_Sudoku.setText("Sudoku");
        button_Sudoku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SudokuActionPerformed(evt);
            }
        });

        button_Scrabble.setText("Scrabble");
        button_Scrabble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ScrabbleActionPerformed(evt);
            }
        });

        button_TTT.setText("TicTacToe");
        button_TTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_TTTActionPerformed(evt);
            }
        });

        button_Dictionary.setText("Dictionary");
        button_Dictionary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_DictionaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(button_Sudoku, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_Scrabble, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(button_TTT, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_Dictionary, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_Scrabble, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_Sudoku, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_TTT, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_Dictionary, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_SudokuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SudokuActionPerformed
        form_Sudoku.setVisible(true);
        form_Main.setVisible(false);
    }//GEN-LAST:event_button_SudokuActionPerformed

    private void button_TTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_TTTActionPerformed
        form_TicTacToe.setVisible(true);
        form_Main.setVisible(false);
        
    }//GEN-LAST:event_button_TTTActionPerformed

    private void button_ScrabbleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ScrabbleActionPerformed
        form_Scrabble.setVisible(true);
        form_Main.setVisible(false);
    }//GEN-LAST:event_button_ScrabbleActionPerformed

    private void button_DictionaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_DictionaryActionPerformed
        form_Dictionary.setVisible(true);
        form_Main.setVisible(false);
    }//GEN-LAST:event_button_DictionaryActionPerformed

    
    public static Form_Sudoku form_Sudoku;
    public static Form_TicTacToe form_TicTacToe;
    public static Form_Main form_Main;
    public static Form_Dictionary form_Dictionary;
    public static Form_Scrabble form_Scrabble;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                form_Main = new Form_Main();
                form_Main.setVisible(true);

                form_TicTacToe = new Form_TicTacToe();
                form_TicTacToe.setVisible(false);
                
                form_Sudoku = new Form_Sudoku();
                form_Sudoku.setVisible(false);
                
                form_Dictionary = new Form_Dictionary();
                form_Dictionary.setVisible(false);
                
                form_Scrabble = new Form_Scrabble();
                form_Scrabble.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Dictionary;
    private javax.swing.JButton button_Scrabble;
    private javax.swing.JButton button_Sudoku;
    private javax.swing.JButton button_TTT;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
