
package TicTacToe.Server;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AnnotatedTTTServer", targetNamespace = "http://TTT.tsa")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AnnotatedTTTServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "switchPlayer", targetNamespace = "http://TTT.tsa", className = "TicTacToe.Server.SwitchPlayer")
    @ResponseWrapper(localName = "switchPlayerResponse", targetNamespace = "http://TTT.tsa", className = "TicTacToe.Server.SwitchPlayerResponse")
    @Action(input = "http://TTT.tsa/AnnotatedTTTServer/switchPlayerRequest", output = "http://TTT.tsa/AnnotatedTTTServer/switchPlayerResponse")
    public String switchPlayer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "npcMove", targetNamespace = "http://TTT.tsa", className = "TicTacToe.Server.NpcMove")
    @ResponseWrapper(localName = "npcMoveResponse", targetNamespace = "http://TTT.tsa", className = "TicTacToe.Server.NpcMoveResponse")
    @Action(input = "http://TTT.tsa/AnnotatedTTTServer/npcMoveRequest", output = "http://TTT.tsa/AnnotatedTTTServer/npcMoveResponse")
    public int npcMove(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

}
