
package TicTacToe.Server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RevisedTTTServer", targetNamespace = "http://TTT.tsa", wsdlLocation = "http://127.0.0.1:9876/TTT?wsdl")
public class RevisedTTTServer
    extends Service
{

    private final static URL REVISEDTTTSERVER_WSDL_LOCATION;
    private final static WebServiceException REVISEDTTTSERVER_EXCEPTION;
    private final static QName REVISEDTTTSERVER_QNAME = new QName("http://TTT.tsa", "RevisedTTTServer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9876/TTT?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REVISEDTTTSERVER_WSDL_LOCATION = url;
        REVISEDTTTSERVER_EXCEPTION = e;
    }

    public RevisedTTTServer() {
        super(__getWsdlLocation(), REVISEDTTTSERVER_QNAME);
    }

    public RevisedTTTServer(WebServiceFeature... features) {
        super(__getWsdlLocation(), REVISEDTTTSERVER_QNAME, features);
    }

    public RevisedTTTServer(URL wsdlLocation) {
        super(wsdlLocation, REVISEDTTTSERVER_QNAME);
    }

    public RevisedTTTServer(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REVISEDTTTSERVER_QNAME, features);
    }

    public RevisedTTTServer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RevisedTTTServer(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AnnotatedTTTServer
     */
    @WebEndpoint(name = "AnnotatedTTTServerPort")
    public AnnotatedTTTServer getAnnotatedTTTServerPort() {
        return super.getPort(new QName("http://TTT.tsa", "AnnotatedTTTServerPort"), AnnotatedTTTServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnnotatedTTTServer
     */
    @WebEndpoint(name = "AnnotatedTTTServerPort")
    public AnnotatedTTTServer getAnnotatedTTTServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://TTT.tsa", "AnnotatedTTTServerPort"), AnnotatedTTTServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REVISEDTTTSERVER_EXCEPTION!= null) {
            throw REVISEDTTTSERVER_EXCEPTION;
        }
        return REVISEDTTTSERVER_WSDL_LOCATION;
    }

}
